name: lakes
channels:
  - conda-forge
  - menpo
  - pytorch
dependencies:
  - geopandas
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - opencv
  - rasterio
  - scipy
  - shapely
  - tensorboard
  - tensorboardx
  - pip
  - pip:
    - torch
    - torchvision
